setwall: remove options and simplify

diff --git a/.local/bin/setwall b/.local/bin/setwall
--- a/.local/bin/setwall
+++ b/.local/bin/setwall
@@ -1,21 +1,19 @@
 #!/usr/bin/env bash
-# DEPENDENCIES: swayimg swaybg
+# DEPENDENCIES: fyi wbg swayimg wallust
 
-readonly WALLPAPER="$HOME/.cache/wallpaper"
+readonly wallpaper_path="$HOME/.cache/wallpaper"
 WALLPAPERS="${WALLPAPERS:-$HOME/Pictures/Wallpapers}"
+GENERATE_COLORSCHEME="${GENERATE_COLORSCHEME:-0}"
 
-update_colorscheme=0
-
-notify_error() {
-  echo "$*" >&2
-  fyi --urgency critical "Error" "$*"
+log_err() {
+  printf 'setwall: %s\n' "$*" >&2
 }
 
 reload_waybar() { pkill -SIGUSR2 waybar; }
 
 generate_colorscheme() {
-  if ! wallust run "$WALLPAPER" -q; then
-    notify_error "Failed to generate the colorscheme"
+  if ! wallust run "$wallpaper_path" -q; then
+    log_err "Failed to generate the colorscheme"
     return 1
   fi
 
@@ -27,59 +25,61 @@ set_wallpaper() {
   wallpaper="$1"
 
   if [[ ! -f "$wallpaper" ]]; then
-    notify_error "$wallpaper: No such file"
+    log_err "$wallpaper: No such file"
     return 1
   fi
 
   absolute_path="$(realpath "$wallpaper")"
-  ln -sf "$absolute_path" "$WALLPAPER"
+  ln -sf "$absolute_path" "$wallpaper_path"
 
-  pkill swaybg
-  swaybg -i "$WALLPAPER" -m fill &>/dev/null &
+  pkill --exact wbg
+  wbg --stretch "$wallpaper_path" &>/dev/null &
   disown
-
-  ((update_colorscheme)) && generate_colorscheme
 }
 
+show_hint() {
+  local nid
+  nid="$(fyi --print-id "Wallpaper Selector" "Press 'Shift+Return' to select")"
+  printf '%s' "${nid#*=}"
+}
+
+close_hint() { fyi --close="$1"; }
+
 pick_wallpaper() {
+  local wallpaper hint_id
+
   if [[ ! -d "$WALLPAPERS" ]]; then
-    notify_error "'$WALLPAPERS': No such directory"
+    log_err "'$WALLPAPERS': No such directory"
     exit 1
   fi
 
-  local nid
-  nid="$(fyi --print-id "Wallpaper Selector" "Press 'Shift+Return' to select")"
-  nid="${nid##*=}"
-
+  hint_id="$(show_hint)"
   wallpaper="$(swayimg -g "$WALLPAPERS" --config ~/.config/swayimg/pick.lua)"
+  close_hint "$hint_id"
 
-  fyi --close="$nid"
-
-  [[ -n "$wallpaper" ]] || exit
-
-  set_wallpaper "$wallpaper"
-}
-
-show_help() {
-  printf "Usage: %s [-f IMAGE] [-d WALLPAPERS_DIR]\n" "$0"
-}
-
-handle_args() {
-  while getopts f:d:uh opt; do
-    case "$opt" in
-      f) set_wallpaper "$OPTARG"; exit ;;
-      d) WALLPAPERS="$OPTARG" ;;
-      u) update_colorscheme=1 ;;
-      h) show_help; exit ;;
-      ?) show_help >&2; exit 2 ;;
-    esac
-  done
-  shift $((OPTIND - 1))
+  [[ -z "$wallpaper" ]] && exit 1
+  printf '%s' "$wallpaper"
 }
 
 main() {
-  (($#)) && handle_args "$@"
-  pick_wallpaper
+  local wallpaper
+
+  if [[ -f "$1" ]]; then
+    wallpaper="$1"
+  elif [[ -d "$1" ]]; then
+    WALLPAPERS="$1"
+  elif [[ ! -z "$1" ]]; then
+    log_err "'$1' No such file or directory"
+    return 1
+  fi
+
+  if [[ -z "$wallpaper" ]]; then
+    wallpaper="$(pick_wallpaper)"
+  fi
+
+  if set_wallpaper "$wallpaper"; then
+    [[ "$GENERATE_COLORSCHEME" -eq 1 ]] && generate_colorscheme
+  fi
 }
 
 main "$@"
